### ISSUE TITLE
New Way of Handling Column Widths is Hard to Override

### ISSUE THREAD

**Issue by black-eye** [fluentform/fluentform#227]
At first I was excited when the custom column width came out, but it seems it brought me more complictions than joy...

I have several custom made classes to handle the different column widths which are now unusable. For ALL the columns there's a default inline style outputting the flex-basis: (e.g. 50% for the 2 columns). I repeat for ALL the columns BY DEFAULT, even thought the sizes are not customly changed.

Please reconsider this behaviour, it makes any custom CSS override a nightmare! The only way, how to handle this is using !important directive. Not to mention tons of unnecessery CSS rules in the code. There's no need for that as all the containers has it's own class describing the number of columns. The inline style is necessary only when you need to override the default width.

The other thing is that the default gap value has changed (from 30px to 18px) for no extra reason.

Could you please make this new experiment optional until it matures? I don't want to change my CSS every other version.

And BTW, the dragging doesn't work in Firefox...

Thanks

**Comment by nkb-bd** [comment]
Hello @black-eye,

Thanks for your detailed feedback. First of all, Firefox dragging issue is now fixed, we will release it with our next update. Also we have updated the default gap as it was before.  Secondly, now you can change the width by typing into the input box. So, you can set the width you set using css by just typing the number, exactly as you need. No need to add css for the column width.

Thanks

**Comment by black-eye** [comment]
OK, thanks for the reply and fixes.

But please reconsider(not) adding the inline styles for the default sizes. They aren't necessary, thus not needed. 

BTW, You tend to do the similar thing in other places as well, e.g. for the default error messages (they're individual even though they are the same), Submit button styles etc. 

I tend to override the basic styles a lot and this is giving me a headache.

Thanks

**Comment by nkb-bd** [comment]
Could please send a screenshot or share more detail about 'default error messages' issue  ?
Thanks

**Comment by nkb-bd** [comment]
Thanks we will discuss this with our team

**Comment by black-eye** [comment]
So I've updated to 4.3.12 and I'm still a bit disaponted that even the default values are output as an inline code. As I mentined, it makes the manual customisation a nightmare. So close to perfection, but still not there... :(

BTW, the column gap was not updated as before - before it was 30px (2 x 15px from each side), now it's only 15px. Please note, that the previous "gap" had two 15px parts, the new one is one simple 15px.

I still hope for the more DRY (Don’t Repeat Repeat Yourself) code...

Thanks
